demo:
  ding:
    appKey: ""
    appSecret: ""
    corpId: ""
    agentId:
  zzd:
    appKey: ""
    appSecret: ""
    corpId:
    domainName: "openplatform.dg-work.cn"
server:
  port: 9001


logging:
  level:
    ROOT: info
    cn.lnexin: debug

spring:
  application:
    name: demo
  thymeleaf:
    prefix:
      classpath: /templates   # 访问template下的html文件需要配置模板，映射
    cache: false # 开发时关闭缓存,不然没法看到实时页面