demo:
  ding:
    appKey: ""
    appSecret: ""
    corpId: ""
    agentId:
  zzd:
    appKey: ""
    appSecret: ""
    tenandId:
    domainName: "openplatform.dg-work.cn"
    protocol: "https"
server:
  port: 9001


logging:
  level:
    ROOT: info
    com.bruce: debug

spring:
  application:
    name: demo
  thymeleaf:
    prefix:
      classpath: /templates   # 访问template下的html文件需要配置模板，映射
    cache: false # 开发时关闭缓存,不然没法看到实时页面
  devtools:
    restart:
      #需要实时更新的目录
      additional-paths: resources/**,static/**,templates/**